#!/command/with-contenv sh

# Create directories just in case at runtime
mkdir -p /var/run/tailscale /var/lib/tailscale

# Start the daemon using explicit 127.0.0.1 loopback
tailscaled \
  --tun=userspace-networking \
  --socks5-server=127.0.0.1:1055 \
  --outbound-http-proxy-listen=127.0.0.1:1055 &
DAEMON_PID=$!

# Wait for the daemon socket to actively respond before moving forward
until tailscale status &> /dev/null; do
    sleep 1
done

# Authenticate with auth key
tailscale up \
  --reset \
  --authkey=${TAILSCALE_AUTHKEY} \
  --hostname=${TS_HOSTNAME:-wa-client}

wait $DAEMON_PID